openapi: 3.0.0
info:
  version: 3.0.0
  title: Manajemen Mahasiswa API
  description: API untuk mengelola data dan alamat
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/dominohdi/mahasiswa/3.0.0

tags:
  - name: mahasiswa
    description: Endpoint untuk manajemen mahasiswa
  - name: address
    description: Endpoint untuk manajemen address

paths:
  /mahasiswa:
    get:
      tags: [mahasiswa]
      summary: Ambil semua data mahasiswa
      responses:
        '200':
          description: Daftar Mahasiswa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mahasiswa'

    post:
      tags: [mahasiswa]
      summary: Tambah Data Mahasiswa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nim:
                  type: string
                  example: "2211104083"
                nama_lengkap:
                  type: string
                  example: "firman maulana"
                email:
                  type: string
                  example: "nyakos@gmail.com"
                no_hp:
                  type: string
                  example: "202482492"
                tanggal_lahir:
                  type: string
                  format: date
                  example: "2000-12-01"
                jenis_kelamin:
                  type: string
                  enum: ["laki-laki", "perempuan"]
      responses:
        '201':
          description: Mahasiswa berhasil ditambahkan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mahasiswa'

  /mahasiswa/{id}:
    get:
      tags: [mahasiswa]
      summary: Ambil data mahasiswa sesuai ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: Data mahasiswa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mahasiswa'

    delete:
      tags: [mahasiswa]
      summary: Hapus data mahasiswa sesuai ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: Mahasiswa berhasil dihapus
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: berhasil menghapus data mahasiswa

components:
  schemas:
    Mahasiswa:
      type: object
      properties:
        id:
          type: integer
          example: 123
        nim:
          type: string
          example: '2211104083'
        nama_lengkap:
          type: string
          example: 'firman maulana'
        email:
          type: string
          example: 'asdd@zxc.cv'
        no_hp:
          type: string
          example: '38923829'
        tanggal_lahir:
          type: string
          format: date
          example: '2000-12-02'
        jenis_kelamin:
          type: string
          enum: [laki-laki, perempuan]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time